spring.application.name=product.manager
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=admin
spring.datasource.password=secret

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
